# Generated by Django 4.2.1 on 2023-05-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('martial_status', models.CharField(max_length=255, null=True)),
                ('Avaliable_vacation', models.IntegerField(null=True)),
                ('approved', models.IntegerField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('birthday', models.DateField(max_length=255, null=True)),
            ],
        ),
    ]
