# Generated by Django 4.2.1 on 2023-05-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='firstname',
            new_name='name',
        ),
    ]
