# Generated by Django 4.2.1 on 2023-05-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_rename_firstname_employees_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Avaliable_vacation',
            new_name='Available_Vacation',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='salary',
            new_name='Salary',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='birthday',
            new_name='date',
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
