# Generated by Django 4.2.1 on 2023-05-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_remove_employees_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
