# Generated by Django 4.2.1 on 2023-05-22 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0007_vacarion_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('from_date', models.DateField(max_length=255, null=True)),
                ('to_date', models.DateField(max_length=255, null=True)),
                ('reason', models.CharField(max_length=1000, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employees')),
            ],
        ),
        migrations.DeleteModel(
            name='vacarion_Employee',
        ),
    ]
