# Generated by Django 4.2.1 on 2023-05-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0008_vacation_employee_delete_vacarion_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation_employee',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
